# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job_id:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: 'projects/1005679379066/locations/global/workloadIdentityPools/github-action-pool/providers/github-action-provider'
        service_account: 'github-action-svc@prj-logging-357706.iam.gserviceaccount.com'
        
    - name: print access token
      run: |-
        echo ${{ steps.auth.outputs.access_token }}         

    - name: Connect to Artifact Registry
      run: |-
        echo ${{ steps.auth.outputs.access_token }} | docker login -u oauth2accesstoken --password-stdin https://asia-southeast2-docker.pkg.dev

    - name: Build Docker image
      run: docker pull nginx:latest
      
    - name: tag Docker image
      run: docker tag nginx:latest asia-southeast2-docker.pkg.dev/prj-logging-357706/dev-repo/nginx:latest

    - name: Publish Docker image to Google Artifact Registry
      run: docker push asia-southeast2-docker.pkg.dev/prj-logging-357706/dev-repo/nginx:latest

    #- id: 'deploy'
    #  uses: 'google-github-actions/deploy-cloudrun@v0'
    #  with:
    #    service: 'hello-cloud-run'
    #    image: 'gcr.io/cloudrun/hello'

    #- name: 'Use output'
    #  run: 'curl "${{ steps.deploy.outputs.url }}"'
